version: 3.0.0-rc2-{build}
branches:
  only:
  - develop
skip_tags: true
image: Visual Studio 2017
configuration: Debug
build:
  verbosity: minimal
test:
  categories:
    except:
    - Speech
    - DocGen
