version: 3.1-{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  categories:
    except:
    - Speech
    - DocGen
    - Network
